---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    #version:
    #includeCRDs: true
    valuesFile: values.yaml

resources:
  - namespace.yaml
