---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    #version:
    # Set this if necessary
    #includeCRDs: true
    valuesFile: values.yaml

namespace: vault
resources:
  - namespace.yaml
