---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.30.0

    namespace: vault
    releaseName: vault

    includeCRDs: true
    valuesFile: vault-values.yaml

resources:
  - namespace.yaml

#configMapGenerator:
#  - name: vault-config
#    files:
#      - config/audit-backend.json
#      - config/auth-methods.json
