---
#injector:
#  #logFormat: "json"
server:
  #auditStorage:
  #  enabled: true
  #  size: 10Gi
  #  storageClass: TODO
  dataStorage:
    size: 1Gi
    storageClass: local-storage
resources:
  requests:
    memory: '256Mi'
  limits:
    memory: '256Mi'
