---
injector:
  enabled: false
  logLevel: info
  logFormat: json

server:
  logLevel: info
  logFormat: json

  #auditStorage:
  #  enabled: true
  #  size: 10Gi
  #  storageClass: TODO

  dataStorage:
    size: 1Gi
    storageClass: node-local-ephemeral
    annotations:
      volumeType: local

  securityContext:
    seccompProfile:
      type: "RuntimeDefault"

  statefulSet:
    securityContext:
      container:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL

resources:
  requests:
    memory: '256Mi'
  limits:
    memory: '256Mi'
