---
#global:
#  enabled: false
#injector:
#  #enabled: true
#  #logFormat: "json"
#  resources:
#    requests:
#      memory: '256Mi'
#      cpu: '250m'
#    limits:
#      memory: '256Mi'
#      cpu: '250m'
#server:
#  enabled: true
  #auditStorage:
  #  enabled: true
  #  size: 1Gi
  #  storageClass: TODO
  #dataStorage:
  #  enabled: true
  #  size: 1Gi
  #  storageClass: TODO
#resources:
#    requests:
#      memory: '256Mi'
#    limits:
#      memory: '256Mi'
#ui:
#  enabled: false
