apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: REPLACE_ME

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: REPLACE_ME
    repo: REPLACE_ME
    version: REPLACE_ME
    #includeCRDs: true
    valuesFile: ../base/values.yaml
    additionalValuesFiles:
      - values.yaml
