---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    version: v1.17.2

    namespace: rook-ceph
    releaseName: rook-ceph

    includeCRDs: true
    valuesFile: operator-values.yaml

resources:
  - namespace.yaml
