---
rbac:
  enabled: true

#resources:

#cephBlockPools:
#cephBlockPoolsVolumeSnapshotClass:
#cephClusterSpec:
#cephFileSystemVolumeSnapshotClass:
#cephFileSystems:
#cephObjectStores:

ingress:
  dashboard:
    enabled: false
