charts:
  local-static-provisioner:
    path: ./manifests/local-static-provisioner/charts/local-static-provisioner
    upstream_repo: https://github.com/kubernetes-sigs/sig-storage-local-static-provisioner
    upstream_path: helm/provisioner/
    ref: v2.8.0
    tracking_branch: vendored-local-static-provisioner-history
