# YAML references are used here to make the format a easier to audit, manage, and maintain. SOPS
# doesn't support specifying multiple AGE public keys with a list... They need to be comma
# delimited strings but at least ignores whitespace sufficiently we can put them on different
# lines.
#
# These groups and references are managed and maintained automatically.

# Application engineers: For private applications running on the cluster that are managed by less
# privileged users, this group only has access to non-infrastructure manifest secrets. Keys from the
# operations group should also be included in this list.
x-app-eng: &manifest-keys >-
  age1a5344plx2p7ar9f2xg4ewmkxn0sppqqm633cafth20kgxtefpeyqgm9fa3,
  age1g3h5t4vlvqfgwdlaqqwrkss2sjzp0uy9fw2cfufrgekjdm6gk44qdc90az

# Operations: Needs access to secrets existing in all manifests. The users primarily manage
# infrastructure manifests but support application engineers.
x-operations-eng: &operations-keys >-
  age1a5344plx2p7ar9f2xg4ewmkxn0sppqqm633cafth20kgxtefpeyqgm9fa3,
  age1g3h5t4vlvqfgwdlaqqwrkss2sjzp0uy9fw2cfufrgekjdm6gk44qdc90az

# Root: Ultimate keys to the kingdom. Sensitive material protected with these keys should only be
# needed during cluster initialization and during any disaster recovery event. This include
# sensitive information such as the Vault root unsealing key, copies of private keys for the other
# services present here. Unauthorized access to this requires rotating all key material in the
# cluster.
x-root-keys: &root-keys >-
  age1a5344plx2p7ar9f2xg4ewmkxn0sppqqm633cafth20kgxtefpeyqgm9fa3

# * Ensure most specific paths are specified in this file before less specific ones
# * Provide the minimum access necessary for each key, keys are cheap and easy to manage. Rotating
#   many credentials is less fun.
creation_rules:
  # Placeholder for app-engine only manifests, each individual app engineer protected file should
  # be specified in a dedicated entry. In the future we may want to get more granular with this
  # targeting specific users.
  - path_regex: manifests/_reference_template/secrets\.yaml$
    age: *app-eng-keys

  # Rule for general manifest secrets, needs to be accessible by anyone writing secrets. If there
  # was a large team working with these it would be worth getting more fine grained with the access
  # grouping here based on responsibilities.
  - path_regex: manifests/.*/secrets\.yaml$
    age: *operations-keys

  # These are encrypted copies of the private keys used by the automated services specified
  # elsewhere in this file (such as the ArgoCD keys). These should only need to be retrieved during
  # cluster initialization and during a DR event. The keys can be rotated without having access.
  - path_regex: secrets/.*/.*\.key$
    age: *root-keys
