extends: default

rules:
  line-length: disable

  # I frequently comment out chunks of sections in YAML while trying to work-out some unrelated bit,
  # leave it in as comments, etc. These are intentionally left without a prefixing space to
  # differentiate them from surrounding comments.
  comments-indentation: disable
  comments:
    require-starting-space: no
