---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: argo-cd
    releaseName: argocd
    repo: https://argoproj.github.io/argo-helm/
    version: 7.6.12
    includeCRDs: true
    # The project claimed this was needed but it may be handled by running the templated resources
    # server-side...
    #apiVersions:
    #- monitoring.coreos.com/v1
    valuesFile: values.yaml

namespace: argocd
resources:
  - namespace.yaml
