---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: argo-cd
    releaseName: argocd
    # This was recommended by argocd project but doesn't work...
    #repo: oci://ghcr.io/argoproj/argo-helm
    repo: https://argoproj.github.io/argo-helm/
    version: 7.6.12
    includeCRDs: true
    #apiVersions:
    #- monitoring.coreos.com/v1
    valuesFile: values.yaml

# Only needed if you need to create the namespace this chart is deploying into. For charts that are
# application/environment specific or have multiple deploys this should happen in the overlay
# directory so the namespace can include deployment specific indicators.
namespace: argocd
resources:
  - namespace.yaml
