---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: meshery
    repo: https://meshery.io/charts/
    version: v0.7.132
    valuesFile: values.yaml

namespace: meshery
resources:
  - namespace.yaml
