---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vault

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: vault
    repo: https://helm.releases.hashicorp.com
    version: 0.30.0

    namespace: vault
    releaseName: vault

    includeCRDs: true
    valuesFile: ../base/vault-values.yaml
    additionalValuesFiles:
      - vault-insecure-values.yaml

resources:
  - ../base/namespace.yaml

patches:
  # This is a test resource that leaked out of the chart. We don't want this in our prod environment
  - target:
      kind: Pod
      name: vault-server-test
      namespace: vault
    patch: |
      $patch: delete
      apiVersion: v1
      kind: Pod
      metadata:
        name: vault-server-test
        namespace: vault
  # Strip out the managed-by so this can be neatly inherited by ArgoCD later on
  - target:
      kind: ".*"
      labelSelector: "app.kubernetes.io/managed-by=Helm"
    patch: |
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1managed-by
