---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: local-static-provisioner
    repo: https://kubernetes-sigs.github.io/sig-storage-local-static-provisioner
    version: 2.0.0

    namespace: kube-system
    releaseName: local-static-provisioner

    valuesFile: values.yaml
