---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../charts/

helmCharts:
  - name: local-static-provisioner
    #repo: https://kubernetes-sigs.github.io/sig-storage-local-static-provisioner
    version: 2.0.0

    namespace: kube-system
    # If you update the following value be sure to update the matching value in the patches below.
    releaseName: local-static-provisioner

    valuesFile: values.yaml

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: DaemonSet
      metadata:
        name: local-static-provisioner
      spec:
        template:
          spec:
            containers:
            - name: provisioner
              securityContext:
                capabilities:
                  drop:
                  - ALL
    target:
      kind: DaemonSet
      # This must match the releaseName above
      name: local-static-provisioner
