---
classes:
- name: vault-local-storage
  hostDir: /var/mnt/system-containers
  mountDir: /mnt/disks
  volumeMode: Filesystem
  fsType: ext4

nodeSelector:
  node-role.kubernetes.io/control-plane: ""

tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
