---
server:
  tls:
    secretName: "vault-tls"
    caBundle: "/vault/userconfig/vault-tls/ca.crt"

  extraVolumes:
    - type: secret
      name: vault-tls
      path: "/vault/userconfig/vault-tls"

  #auditStorage:
  #  enabled: true
  #  size: 2Gi
  #  storageClass: TODO
