---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../_out/charts/

resources:
  - namespace.yaml
  - node-local-ephemeral-v0.0.31.yaml

# Strip out all Helm-related labels so resources can be cleanly adopted by ArgoCD
patches:
  - target:
      kind: ".*"
      labelSelector: "app.kubernetes.io/managed-by=Helm"
    patch: |-
      - op: remove
        path: /metadata/labels/app.kubernetes.io~1managed-by
