apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base/

# Strip out all Helm-related labels so resources can be cleanly adopted by ArgoCD
labels:
  - pairs:
      app.kubernetes.io/managed-by: null
      helm.sh/chart: null
    includeSelectors: false
    includeTemplates: true
