---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../_out/charts/

resources:
  - namespace.yaml
  - local-path-provisioner-manifests.yaml

# Strip out all Helm-related labels so resources can be cleanly adopted by ArgoCD
#patches:
#  - target:
#      kind: ".*"
#    patch: |-
#      - op: remove
#        path: /metadata/labels/app.kubernetes.io~1managed-by
#      - op: remove
#        path: /metadata/labels/helm.sh~1chart

#  - target:
#      kind: "Deployment|StatefulSet|DaemonSet|Job|CronJob"
#    patch: |-
#      - op: remove
#        path: /spec/template/metadata/labels/app.kubernetes.io~1managed-by
#      - op: remove
#        path: /spec/template/metadata/labels/helm.sh~1chart

labels:
  - pairs:
      app.kubernetes.io/managed-by: ""
      helm.sh/chart: ""
    includeSelectors: false
    includeTemplates: true
