---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyverno

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    version: 3.3.2

    namespace: kyverno
    releaseName: kyverno

    includeCRDs: true
    valuesFile: values.yaml
  - name: kyverno-policies
    repo: https://kyverno.github.io/kyverno/

    namespace: kyverno
    releaseName: kyverno-policies

    version: 3.3.0
    valuesFile: values.yaml

resources:
  - namespace.yaml
