---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kyverno

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: kyverno
    repo: https://kyverno.github.io/kyverno/
    version: 3.3.2
    includeCRDs: true
    namespace: kyverno
    valuesFile: values.yaml
