---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: rook-ceph
    repo: https://charts.rook.io/release
    version: v1.15.4
    #includeCRDs: true
    valuesFile: values.yaml

namespace: rook-ceph
resources:
  - namespace.yaml
