---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

helmGlobals:
  chartHome: ../../../_out/charts/

# Roughly setting up according to this:

helmCharts:
  # TODO: there are several different helm charts for loki here, this is the base but I'm not sure
  # its the one I want...
  #- name: loki
  #  repo: https://grafana.github.io/helm-charts
  #  #version:

  #  namespace: observability
  #  releaseName: loki

  #  # Set this if necessary
  #  #includeCRDs: true
  #  #valuesFile: values.yaml
  # TODO: There are a few other pieces of software fulfilling this role that are equally
  # low-resource and might provide better performance or first pass filtering that are worth
  # exploring...
  - name: promtail
    repo: https://grafana.github.io/helm-charts
    #version:

    namespace: observability
    releaseName: grafana

    # Set this if necessary
    #includeCRDs: true
    #valuesFile: values.yaml
  # TODO: there are several different helm charts for tempo here, this is the base but I'm not sure
  # its the one I want...
  - name: tempo
    repo: https://grafana.github.io/helm-charts
    #version:

    namespace: observability
    releaseName: grafana

    # Set this if necessary
    #includeCRDs: true
    #valuesFile: values.yaml
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    #version:

    namespace: observability
    releaseName: grafana

    # Set this if necessary
    #includeCRDs: true
    #valuesFile: values.yaml

# Only needed if you need to create the namespace this chart is deploying into. For charts that are
# application/environment specific or have multiple deploys this should happen in the overlay
# directory so the namespace can include deployment specific indicators.
resources:
  - namespace.yaml
