alertmanager:
  persistentVolume:
    enabled: true
  replicas: 1
  resources:
    limits:
      memory: 1.4Gi
    requests:
      cpu: 1
      memory: 1024Mi
  statefulSet:
    enabled: true

compactor:
  persistentVolume:
    size: 1Gi
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 1
      memory: 512Mi

distributor:
  replicas: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 1
      memory: 512Mi

ingester:
  persistentVolume:
    size: 1Gi
  replicas: 1
  resources:
    limits:
      memory: 1Gi
    requests:
      cpu: 2
      memory: 784Mi
  topologySpreadConstraints: {}
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: target # support for enterprise.legacyLabels
                operator: In
                values:
                  - ingester
          topologyKey: 'kubernetes.io/hostname'

        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - ingester
          topologyKey: 'kubernetes.io/hostname'

  zoneAwareReplication:
    topologyKey: 'kubernetes.io/hostname'

admin-cache:
  enabled: true
  replicas: 1

chunks-cache:
  enabled: true
  replicas: 1

index-cache:
  enabled: true
  replicas: 1

metadata-cache:
  enabled: true

results-cache:
  enabled: true
  replicas: 1

minio:
  enabled: true

overrides_exporter:
  replicas: 1
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

querier:
  replicas: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 2
      memory: 784Mi

query_frontend:
  replicas: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 2
      memory: 784Mi

ruler:
  replicas: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 1
      memory: 784Mi

store_gateway:
  persistentVolume:
    size: 1Gi
  replicas: 1
  resources:
    limits:
      memory: 1024Mi
    requests:
      cpu: 1
      memory: 764Mi
  topologySpreadConstraints: {}
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        - labelSelector:
            matchExpressions:
              - key: target # support for enterprise.legacyLabels
                operator: In
                values:
                  - store-gateway
          topologyKey: 'kubernetes.io/hostname'

        - labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/component
                operator: In
                values:
                  - store-gateway
          topologyKey: 'kubernetes.io/hostname'
  zoneAwareReplication:
    topologyKey: 'kubernetes.io/hostname'

nginx:
  replicas: 1
  resources:
    limits:
      memory: 731Mi
    requests:
      cpu: 1
      memory: 512Mi

# Grafana Enterprise Metrics feature related
admin_api:
  replicas: 1
  resources:
    limits:
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 64Mi

gateway:
  replicas: 1
  resources:
    limits:
      memory: 731Mi
    requests:
      cpu: 1
      memory: 512Mi
