---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: cilium
    repo: https://helm.cilium.io/
    version: 1.17.2

    namespace: kube-system
    releaseName: cilium

    includeCRDs: true
    valuesFile: cilium-values.yaml

resources:
  #- kyverno-policy-exceptions.yaml
