---
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: cilium-core-capabilities-exception
  namespace: kube-system
  annotations:
    description: >-
      Cilium is the system's CNI and as such it needs more permissions that others, primarily
      CAP_NET_RAW, CAP_NET_BIND_SERVICE, CAP_BPF, and CAP_NET_ADMIN. There may be others. The
      generated charts currently do not attempt to drop any permissions which can likely be
      tightened up via a kustomization patch.

      The risk of the additional permissions here is minimal and has been formally accepted. This
      exception is allowed to enter the production cluster.

      TODO(low): Identify required capabilities and create patch to drop unecessary permissions.
spec:
  match:
    all:
    - resources:
        namespaces:
          - kube-system
        kinds:
          - DaemonSet
          - Deployment
        names:
          - cilium
          - cilium-operator
  exceptions:
  - policyName: disallow-capabilities-strict
    ruleNames:
      - autogen-require-drop-all
---
apiVersion: kyverno.io/v2beta1
kind: PolicyException
metadata:
  name: cilium-envoy-capabilities-exception
  namespace: kube-system
  annotations:
    description: >-
      Envoy acts as a privileged intercepting proxy and need more privileges than your standard
      container.

      TODO(medium): I've omitted all the requirements here but we could enforce a different
      restricted set to ensure it stays as low as possible.
spec:
  match:
    all:
    - resources:
        namespaces:
          - kube-system
        kinds:
          - DaemonSet
          - Pod
        names:
          - cilium-envoy
          - cilium-envoy-*
  exceptions:
  - policyName: disallow-capabilities-strict
    ruleNames:
      - autogen-adding-capabilities-strict
      - adding-capabilities-strict
