apiVersion: kyverno.io/v2
kind: PolicyException
metadata:
  name: cilium-cluster-capabilities-exception
  namespace: kube-system
spec:
  background: true
  match:
    any:
    - resources:
        namespaces:
          - kube-system
        kinds:
          - CronJob
          - DaemonSet
          - Deployment
          - Job
        names:
          - cilium
          - cilium-operator
          - hubble-generate-certs
  exceptions:
  - policyName: disallow-capabilities-strict
    ruleNames:
      - require-drop-all
      - autogen-require-drop-all
      - autogen-cronjob-require-drop-all
      - adding-capabilities-strict
