---
apiVersion: "cilium.io/v2"
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: host-cluster-traffic
  namespace: kube-system
  labels:
    "io.cilium.policy.audit-mode": "enabled"
spec:
  endpointSelector:
    matchExpressions:
      - { key: host, operator: Exists }

  egress:
    - toEntities:
        - kube-apiserver
      toPorts:
        - ports:
          - port: "2380"
            protocol: TCP

  ingress:
    - {}
