---
apiVersion: "cilium.io/v2"
kind: CiliumNetworkPolicy
metadata:
  name: permitted-cluster-dns
  namespace: kube-system
  labels:
    "io.cilium.policy.audit-mode": "enabled"
spec:
  endpointSelector:
    matchExpressions:
      - { key: kube-dns, operator: Exists }

  egress:
    - toCIDRSet:
        # Cloudflare addresses
        - cidr: "1.1.1.1/32"
        - cidr: "1.0.0.1/32"
        - cidr: "2606:4700:4700::1111/128"
        - cidr: "2606:4700:4700::1001/128"
      toPorts:
        - ports:
          - port: "53"
            protocol: TCP
          - port: "53"
            protocol: UDP

  ingress:
    # Allow the Kube API server to access the health endpoint used by liveness and readiness probes
    # (port 8080/tcp). The API server also talks to port 8081/tcp supposedly for accessing metrics
    # but I couldn't find any details on this behavior. Leaving for now...
    - fromEntities:
        - kube-apiserver
      toPorts:
        - ports:
          - port: "8080"
            protocol: TCP
          - port: "8081"
            protocol: TCP

    - fromEndpoints:
        # Match all pods, everything within the cluster is permitted to query the cluster DNS
        # servers, but only the CoreDNS pods are allowed to talk to our upstreams.
        - {}
      toPorts:
        - ports:
          - port: "53"
            protocol: UDP
          - port: "53"
            protocol: TCP
          # Can restrict lookups to an explicit allow-list of queries...
          #rules:
          #  dns:
          #    - matchPattern: "*.grayiron.io"
