---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: cert-manager

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.17.2

    namespace: cert-manager
    releaseName: cert-manager

    includeCRDs: true
    valuesFile: values.yaml

resources:
  - namespace.yaml
