---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: REPLACE_ME
    repo: REPLACE_ME
    version: REPLACE_ME
    # Set this if necessary
    #includeCRDs: true
    valuesFile: values.yaml

# Only needed if you need to create the namespace this chart is deploying into. For charts that are
# application/environment specific or have multiple deploys this should happen in the overlay
# directory so the namespace can include deployment specific indicators.
namespace: REPLACE_ME
resources:
  - namespace.yaml
