---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This can be useful for diagnostics and tracking of mutations and for tracing where particular
# deployments were sourced from. We may have use for these in origin tracking in the future but for
# now they're selectively turned on for manifest diagnostics.
#buildMetadata:
#- originAnnotations
#- transformerAnnotations

namespace: REPLACE_ME

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: REPLACE_ME
    repo: REPLACE_ME
    version: REPLACE_ME

    namespace: REPLACE_ME
    releaseName: REPLACE_ME

    # Set this if necessary
    #includeCRDs: true
    valuesFile: values.yaml

# Only needed if you need to create the namespace this chart is deploying into. For charts that are
# application/environment specific or have multiple deploys this should happen in the overlay
# directory so the namespace can include deployment specific indicators.
resources:
  - namespace.yaml
