---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# This can be useful for diagnostics and tracking of mutations and for tracing where particular
# deployments were sourced from. We may have use for these in origin tracking in the future but for
# now they're selectively turned on for manifest diagnostics.
#buildMetadata:
#- originAnnotations
#- transformerAnnotations

namespace: REPLACE_ME # Default namespace used for generated resources

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: REPLACE_ME    # Name of the chart within the repo "vault"
    repo: REPLACE_ME    # URL such as https://helm.releases.hashicorp.com
    version: REPLACE_ME # Tagged version available in the repo such as 0.30.0

    namespace: REPLACE_ME   # Which namespace this will be deployed into, should match namespace above.
    releaseName: REPLACE_ME # Deployed base name of this instance of this helm chart

    #includeCRDs: true      # Set this if the chart deploys custom CRDs (most operators do)
    valuesFile: values.yaml # File containing the specific configuration for this rendered instance of the template

# Only needed if you need to create the namespace this chart is deploying into. For charts that are
# application/environment specific or have multiple deploys this should happen in the overlay
# directory so the namespace can include deployment specific indicators.
resources:
  - namespace.yaml
