---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: remote-backups
provisioner: nfs.csi.k8s.io
parameters:
  server: nfs-service.nfs-wireguard.svc
  share: /mnt/primary-storage/tlp-white-encrypted-backups
  subDir: firmament/${pvc.metadata.namespace}/${pvc.metadata.name}
reclaimPolicy: Retain
volumeBindingMode: Immediate
allowVolumeExpansion: true
