---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: tlp-red-traffic-datasets
spec:
  capacity:
    storage: 100Ti
  accessModes:
    - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: nfs.csi.k8s.io
    readOnly: true
    volumeHandle: tlp-red-traffic-datasets
    volumeAttributes:
      server: nfs-service.nfs-wireguard.svc
      share: "/mnt/primary-storage/tlp-red-traffic-datasets"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: tlp-red-traffic-datasets-pvc
spec:
  accessModes:
    - ReadOnlyMany
  resources:
    requests:
      storage: 100Ti
  volumeName: tlp-red-traffic-datasets-pv
