---
# Ok, this one is kind of dumb but I needed to get logs from the machines before the talosctl API
# came up, because it was failing to come up... You don't actually need a service to receive these,
# if nothing receives them they get silently discarded. If, however, a dumb developer opens up a
# udp netcat listener in their shell with `ncat -kul 46721`.
#
# If you really want to get special, this could be overridden with each server adding its specific
# tag so you can better distinguish it. I recommend redirecting the output to a file (maybe using
# tee to see them as well) and use `jq` to sift though the results.
machine:
  logging:
    destinations:
      - endpoint: "udp://10.5.0.1:46721/"
        format: "json_lines"
        extraTags:
          cluster: firmament-integration
---
# These are kernel logs, I believe they're separate from the above logs and I'm unclear whether the
# same UDP rules apply to these. Worth a shot... I'll send them to a different port to
# differentiate them when running netcat...
apiVersion: v1alpha1
kind: KmsgLogConfig
name: remote-log
url: udp://10.5.0.1:46722/
