---
server:
  #standalone:
  #  enabled: false

  #ha:
  #  enabled: true
  #  replicas: 3
  #  raft:
  #    enabled: true

  tls:
    enabled: true
    secretName: "vault-tls"
    caBundle: "/vault/userconfig/vault-tls/ca.crt"

  extraVolumes:
    - type: secret
      name: vault-tls
      path: "/vault/userconfig/vault-tls"
