---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: rook-ceph

helmGlobals:
  chartHome: ../../../_out/charts/

helmCharts:
  - name: rook-ceph-cluster
    repo: https://charts.rook.io/release
    version: v1.15.4

    namespace: rook-ceph
    releaseName: rook-ceph-cluster

    includeCRDs: true
    valuesFile: cluster-values.yaml
